# Generated by Django 3.0.5 on 2020-05-08 23:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CSA', 'Clothing, Shoes & Accessories'), ('CE', 'Consumer Electronics'), ('TH', 'Toys & Hobbies'), ('HG', 'Home & Garden'), ('PS', 'Pet Supplies'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('A', 'Antiques'), ('CTN', 'Computers/Tablets & Networking'), ('DB', 'Dolls & Bears'), ('C', 'Crafts'), ('SG', 'Sporting Goods'), ('B', 'Books'), ('M', 'Motors'), ('BI', 'Business & Industrial')], max_length=3)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('posted', models.DateTimeField(blank=True, default='2020-05-09 01:17:29', null=True)),
                ('image', models.ImageField(blank=True, upload_to='advert_images')),
                ('archive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(blank=True, default='2020-05-09 01:17:29', null=True)),
                ('comment', models.BooleanField(default=False)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Advert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateTimeField(blank=True, default='2020-05-09 01:17:29', null=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Advert')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
