# Generated by Django 3.0.5 on 2020-04-29 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('A', 'Antiques'), ('TH', 'Toys & Hobbies'), ('DB', 'Dolls & Bears'), ('CTN', 'Computers/Tablets & Networking'), ('CSA', 'Clothing, Shoes & Accessories'), ('C', 'Crafts'), ('HG', 'Home & Garden'), ('SG', 'Sporting Goods'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('PS', 'Pet Supplies'), ('M', 'Motors'), ('B', 'Books'), ('BI', 'Business & Industrial'), ('CE', 'Consumer Electronics')], max_length=3)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, db_index=True, upload_to='advert_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
