# Generated by Django 3.0.5 on 2020-05-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('C', 'Crafts'), ('SG', 'Sporting Goods'), ('BI', 'Business & Industrial'), ('DB', 'Dolls & Bears'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('B', 'Books'), ('HG', 'Home & Garden'), ('TH', 'Toys & Hobbies'), ('A', 'Antiques'), ('CE', 'Consumer Electronics'), ('M', 'Motors'), ('PS', 'Pet Supplies'), ('CTN', 'Computers/Tablets & Networking'), ('CSA', 'Clothing, Shoes & Accessories')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-09 01:20:00', null=True),
        ),
        migrations.AlterField(
            model_name='advertcomments',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-09 01:20:00', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-09 01:20:00', null=True),
        ),
    ]
