# Generated by Django 3.0.5 on 2020-04-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200429_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('TH', 'Toys & Hobbies'), ('BI', 'Business & Industrial'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('C', 'Crafts'), ('DB', 'Dolls & Bears'), ('CSA', 'Clothing, Shoes & Accessories'), ('HG', 'Home & Garden'), ('CTN', 'Computers/Tablets & Networking'), ('B', 'Books'), ('M', 'Motors'), ('A', 'Antiques'), ('SG', 'Sporting Goods'), ('PS', 'Pet Supplies'), ('CE', 'Consumer Electronics')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, upload_to='advert_images'),
        ),
    ]
