# Generated by Django 3.0.5 on 2020-05-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200509_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('BI', 'Business & Industrial'), ('CSA', 'Clothing, Shoes & Accessories'), ('TH', 'Toys & Hobbies'), ('A', 'Antiques'), ('B', 'Books'), ('CTN', 'Computers/Tablets & Networking'), ('DB', 'Dolls & Bears'), ('PS', 'Pet Supplies'), ('SG', 'Sporting Goods'), ('CE', 'Consumer Electronics'), ('M', 'Motors'), ('HG', 'Home & Garden'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('C', 'Crafts')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-09 23:58:38', null=True),
        ),
        migrations.AlterField(
            model_name='advertcomments',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bought'),
        ),
        migrations.AlterField(
            model_name='advertcomments',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-09 23:58:38', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-09 23:58:38', null=True),
        ),
    ]
