# Generated by Django 3.0.5 on 2020-05-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200501_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('CE', 'Consumer Electronics'), ('M', 'Motors'), ('SG', 'Sporting Goods'), ('CTN', 'Computers/Tablets & Networking'), ('DB', 'Dolls & Bears'), ('B', 'Books'), ('PS', 'Pet Supplies'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('TH', 'Toys & Hobbies'), ('CSA', 'Clothing, Shoes & Accessories'), ('A', 'Antiques'), ('BI', 'Business & Industrial'), ('C', 'Crafts'), ('HG', 'Home & Garden')], max_length=3),
        ),
    ]
