# Generated by Django 3.0.5 on 2020-05-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200510_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('PS', 'Pet Supplies'), ('BI', 'Business & Industrial'), ('HG', 'Home & Garden'), ('M', 'Motors'), ('SG', 'Sporting Goods'), ('A', 'Antiques'), ('CE', 'Consumer Electronics'), ('DB', 'Dolls & Bears'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('B', 'Books'), ('CTN', 'Computers/Tablets & Networking'), ('CSA', 'Clothing, Shoes & Accessories'), ('C', 'Crafts'), ('TH', 'Toys & Hobbies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-10 00:17:23', null=True),
        ),
        migrations.AlterField(
            model_name='advertcomments',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-10 00:17:23', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-10 00:17:23', null=True),
        ),
    ]
