# Generated by Django 3.0.5 on 2020-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200501_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('SCF', 'Sports Mem, Cards & Fan Shop'), ('DB', 'Dolls & Bears'), ('CTN', 'Computers/Tablets & Networking'), ('HG', 'Home & Garden'), ('A', 'Antiques'), ('PS', 'Pet Supplies'), ('B', 'Books'), ('C', 'Crafts'), ('BI', 'Business & Industrial'), ('SG', 'Sporting Goods'), ('CSA', 'Clothing, Shoes & Accessories'), ('CE', 'Consumer Electronics'), ('TH', 'Toys & Hobbies'), ('M', 'Motors')], max_length=3),
        ),
    ]
