# Generated by Django 3.0.5 on 2020-05-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200510_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('CTN', 'Computers/Tablets & Networking'), ('SG', 'Sporting Goods'), ('CSA', 'Clothing, Shoes & Accessories'), ('C', 'Crafts'), ('CE', 'Consumer Electronics'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('BI', 'Business & Industrial'), ('HG', 'Home & Garden'), ('PS', 'Pet Supplies'), ('M', 'Motors'), ('DB', 'Dolls & Bears'), ('B', 'Books'), ('A', 'Antiques'), ('TH', 'Toys & Hobbies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-10 00:18:49', null=True),
        ),
        migrations.AlterField(
            model_name='advertcomments',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-10 00:18:49', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-10 00:18:49', null=True),
        ),
    ]
