# Generated by Django 3.0.5 on 2020-05-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200501_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('C', 'Crafts'), ('SG', 'Sporting Goods'), ('CTN', 'Computers/Tablets & Networking'), ('CE', 'Consumer Electronics'), ('A', 'Antiques'), ('DB', 'Dolls & Bears'), ('TH', 'Toys & Hobbies'), ('M', 'Motors'), ('PS', 'Pet Supplies'), ('HG', 'Home & Garden'), ('BI', 'Business & Industrial'), ('B', 'Books'), ('CSA', 'Clothing, Shoes & Accessories'), ('SCF', 'Sports Mem, Cards & Fan Shop')], max_length=3),
        ),
    ]
