# Generated by Django 3.0.5 on 2020-05-09 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200510_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('C', 'Crafts'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('CTN', 'Computers/Tablets & Networking'), ('BI', 'Business & Industrial'), ('CSA', 'Clothing, Shoes & Accessories'), ('CE', 'Consumer Electronics'), ('DB', 'Dolls & Bears'), ('B', 'Books'), ('PS', 'Pet Supplies'), ('M', 'Motors'), ('A', 'Antiques'), ('TH', 'Toys & Hobbies'), ('HG', 'Home & Garden'), ('SG', 'Sporting Goods')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-10 00:30:14', null=True),
        ),
        migrations.AlterField(
            model_name='advertcomments',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bought'),
        ),
        migrations.AlterField(
            model_name='advertcomments',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-10 00:30:14', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-10 00:30:14', null=True),
        ),
    ]
