# Generated by Django 3.0.5 on 2020-05-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200502_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('HG', 'Home & Garden'), ('CSA', 'Clothing, Shoes & Accessories'), ('PS', 'Pet Supplies'), ('C', 'Crafts'), ('B', 'Books'), ('M', 'Motors'), ('TH', 'Toys & Hobbies'), ('SG', 'Sporting Goods'), ('DB', 'Dolls & Bears'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('CTN', 'Computers/Tablets & Networking'), ('BI', 'Business & Industrial'), ('CE', 'Consumer Electronics'), ('A', 'Antiques')], max_length=3),
        ),
    ]
