# Generated by Django 3.0.5 on 2020-05-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200502_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='posted',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('SCF', 'Sports Mem, Cards & Fan Shop'), ('BI', 'Business & Industrial'), ('C', 'Crafts'), ('A', 'Antiques'), ('CE', 'Consumer Electronics'), ('DB', 'Dolls & Bears'), ('CSA', 'Clothing, Shoes & Accessories'), ('M', 'Motors'), ('B', 'Books'), ('HG', 'Home & Garden'), ('SG', 'Sporting Goods'), ('CTN', 'Computers/Tablets & Networking'), ('TH', 'Toys & Hobbies'), ('PS', 'Pet Supplies')], max_length=3),
        ),
    ]
