# Generated by Django 3.0.5 on 2020-05-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200503_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('HG', 'Home & Garden'), ('B', 'Books'), ('M', 'Motors'), ('BI', 'Business & Industrial'), ('PS', 'Pet Supplies'), ('A', 'Antiques'), ('DB', 'Dolls & Bears'), ('C', 'Crafts'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('CTN', 'Computers/Tablets & Networking'), ('CE', 'Consumer Electronics'), ('SG', 'Sporting Goods'), ('TH', 'Toys & Hobbies'), ('CSA', 'Clothing, Shoes & Accessories')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-03 20:58', null=True),
        ),
    ]
