# Generated by Django 3.0.5 on 2020-05-04 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20200503_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('B', 'Books'), ('CE', 'Consumer Electronics'), ('CTN', 'Computers/Tablets & Networking'), ('BI', 'Business & Industrial'), ('DB', 'Dolls & Bears'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('CSA', 'Clothing, Shoes & Accessories'), ('C', 'Crafts'), ('PS', 'Pet Supplies'), ('SG', 'Sporting Goods'), ('TH', 'Toys & Hobbies'), ('A', 'Antiques'), ('M', 'Motors'), ('HG', 'Home & Garden')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-04 22:21:31', null=True),
        ),
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(blank=True, default='2020-05-04 22:21:31', null=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Advert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
