# Generated by Django 3.0.5 on 2020-05-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200504_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('B', 'Books'), ('CE', 'Consumer Electronics'), ('SG', 'Sporting Goods'), ('HG', 'Home & Garden'), ('TH', 'Toys & Hobbies'), ('CSA', 'Clothing, Shoes & Accessories'), ('M', 'Motors'), ('PS', 'Pet Supplies'), ('CTN', 'Computers/Tablets & Networking'), ('C', 'Crafts'), ('DB', 'Dolls & Bears'), ('A', 'Antiques'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('BI', 'Business & Industrial')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-04 23:30:32', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='advert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Advert'),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-04 23:30:32', null=True),
        ),
    ]
