# Generated by Django 3.0.5 on 2020-05-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200504_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('C', 'Crafts'), ('A', 'Antiques'), ('CTN', 'Computers/Tablets & Networking'), ('BI', 'Business & Industrial'), ('DB', 'Dolls & Bears'), ('B', 'Books'), ('HG', 'Home & Garden'), ('SG', 'Sporting Goods'), ('M', 'Motors'), ('TH', 'Toys & Hobbies'), ('CSA', 'Clothing, Shoes & Accessories'), ('CE', 'Consumer Electronics'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('PS', 'Pet Supplies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-05 17:17:27', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-05 17:17:27', null=True),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Advert')),
            ],
        ),
    ]
