# Generated by Django 3.0.5 on 2020-05-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200505_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='category',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='description',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='image',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='price',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='title',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='user',
        ),
        migrations.AddField(
            model_name='archive',
            name='advert',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Advert'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('SCF', 'Sports Mem, Cards & Fan Shop'), ('HG', 'Home & Garden'), ('B', 'Books'), ('PS', 'Pet Supplies'), ('M', 'Motors'), ('SG', 'Sporting Goods'), ('CSA', 'Clothing, Shoes & Accessories'), ('BI', 'Business & Industrial'), ('CE', 'Consumer Electronics'), ('CTN', 'Computers/Tablets & Networking'), ('A', 'Antiques'), ('TH', 'Toys & Hobbies'), ('C', 'Crafts'), ('DB', 'Dolls & Bears')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-05 18:01:35', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-05 18:01:35', null=True),
        ),
    ]
