# Generated by Django 3.0.5 on 2020-05-05 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20200505_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='advert',
        ),
        migrations.AddField(
            model_name='archive',
            name='category',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='image',
            field=models.ImageField(blank=True, upload_to='advert_images'),
        ),
        migrations.AddField(
            model_name='archive',
            name='posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('C', 'Crafts'), ('M', 'Motors'), ('A', 'Antiques'), ('BI', 'Business & Industrial'), ('TH', 'Toys & Hobbies'), ('PS', 'Pet Supplies'), ('B', 'Books'), ('CE', 'Consumer Electronics'), ('SG', 'Sporting Goods'), ('DB', 'Dolls & Bears'), ('CTN', 'Computers/Tablets & Networking'), ('CSA', 'Clothing, Shoes & Accessories'), ('HG', 'Home & Garden'), ('SCF', 'Sports Mem, Cards & Fan Shop')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-05 18:04:13', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-05 18:04:13', null=True),
        ),
    ]
