# Generated by Django 3.0.5 on 2020-05-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200505_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('DB', 'Dolls & Bears'), ('CE', 'Consumer Electronics'), ('HG', 'Home & Garden'), ('PS', 'Pet Supplies'), ('BI', 'Business & Industrial'), ('TH', 'Toys & Hobbies'), ('A', 'Antiques'), ('CTN', 'Computers/Tablets & Networking'), ('C', 'Crafts'), ('SG', 'Sporting Goods'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('B', 'Books'), ('M', 'Motors'), ('CSA', 'Clothing, Shoes & Accessories')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-05 18:09:52', null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-05 18:09:52', null=True),
        ),
    ]
