# Generated by Django 3.0.5 on 2020-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200505_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('PS', 'Pet Supplies'), ('BI', 'Business & Industrial'), ('DB', 'Dolls & Bears'), ('HG', 'Home & Garden'), ('B', 'Books'), ('M', 'Motors'), ('TH', 'Toys & Hobbies'), ('A', 'Antiques'), ('CTN', 'Computers/Tablets & Networking'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('CSA', 'Clothing, Shoes & Accessories'), ('SG', 'Sporting Goods'), ('C', 'Crafts'), ('CE', 'Consumer Electronics')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-05 19:01:49', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-05 19:01:49', null=True),
        ),
    ]
