# Generated by Django 3.0.5 on 2020-05-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200505_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bought',
            name='archive',
        ),
        migrations.AddField(
            model_name='advert',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('PS', 'Pet Supplies'), ('DB', 'Dolls & Bears'), ('TH', 'Toys & Hobbies'), ('BI', 'Business & Industrial'), ('SG', 'Sporting Goods'), ('CE', 'Consumer Electronics'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('CSA', 'Clothing, Shoes & Accessories'), ('CTN', 'Computers/Tablets & Networking'), ('HG', 'Home & Garden'), ('M', 'Motors'), ('A', 'Antiques'), ('C', 'Crafts'), ('B', 'Books')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-05 19:49:26', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-05 19:49:26', null=True),
        ),
    ]
