# Generated by Django 3.0.5 on 2020-05-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200505_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('TH', 'Toys & Hobbies'), ('A', 'Antiques'), ('CE', 'Consumer Electronics'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('HG', 'Home & Garden'), ('B', 'Books'), ('SG', 'Sporting Goods'), ('CSA', 'Clothing, Shoes & Accessories'), ('C', 'Crafts'), ('DB', 'Dolls & Bears'), ('CTN', 'Computers/Tablets & Networking'), ('BI', 'Business & Industrial'), ('M', 'Motors'), ('PS', 'Pet Supplies')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-05 20:28:20', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-05 20:28:20', null=True),
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
