# Generated by Django 3.0.5 on 2020-05-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200505_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('HG', 'Home & Garden'), ('DB', 'Dolls & Bears'), ('TH', 'Toys & Hobbies'), ('CE', 'Consumer Electronics'), ('SG', 'Sporting Goods'), ('CTN', 'Computers/Tablets & Networking'), ('M', 'Motors'), ('SCF', 'Sports Mem, Cards & Fan Shop'), ('PS', 'Pet Supplies'), ('CSA', 'Clothing, Shoes & Accessories'), ('BI', 'Business & Industrial'), ('A', 'Antiques'), ('C', 'Crafts'), ('B', 'Books')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posted',
            field=models.DateTimeField(blank=True, default='2020-05-05 20:29:19', null=True),
        ),
        migrations.AlterField(
            model_name='bought',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Advert'),
        ),
        migrations.AlterField(
            model_name='bought',
            name='date',
            field=models.DateTimeField(blank=True, default='2020-05-05 20:29:19', null=True),
        ),
    ]
